"""
DocMind — Answer Quality Analytics

Loads and summarizes the results generated by:

    python -m app.evaluation.answer_evaluator

This module is independent from the Streamlit UI so the same evaluation
results can be reused by the dashboard, reports, and future analysis.

CSV schema used by the current answer evaluator:

    question
    difficulty
    category
    expected_sources
    matched_sources
    expected_source_found
    answer
    abstention_expected
    abstained
    abstention_correct
    retrieved_count
    source_count
    context_characters
    context_relevance_score
    token_support_score
    groundedness_score
    citation_score
    citation_correct
    citation_mode
    citation_numbers
    suspicious_content
    suspicious_patterns
    answer_length
    retrieval_ms
    context_ms
    generation_ms
    total_ms
    retrieval_mode
    top_k
    top_hybrid_score
    top_reranker_score
    retrieval_error
    context_error
    generation_error
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

import pandas as pd


# ============================================================================
# PATHS
# ============================================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

RESULTS_PATH = PROJECT_ROOT / "docs" / "answer_evaluation_results.csv"


# ============================================================================
# LOADING
# ============================================================================

def results_exist() -> bool:
    """Return True when answer evaluation results are available."""
    return RESULTS_PATH.exists()


def load_answer_quality_results() -> pd.DataFrame:
    """
    Load the answer-quality evaluation CSV.

    Returns:
        pandas.DataFrame

    Raises:
        FileNotFoundError:
            When the evaluator has not generated its CSV yet.
        ValueError:
            When the CSV exists but contains no rows.
    """

    if not RESULTS_PATH.exists():
        raise FileNotFoundError(
            f"Answer evaluation results were not found at:\n"
            f"{RESULTS_PATH}\n\n"
            "Run:\n"
            "python -m app.evaluation.answer_evaluator"
        )

    df = pd.read_csv(RESULTS_PATH)

    if df.empty:
        raise ValueError(
            "The answer evaluation results file is empty."
        )

    return df


# ============================================================================
# NUMERIC HELPERS
# ============================================================================

def _numeric_column(
    df: pd.DataFrame,
    column: str,
) -> pd.Series:
    """Return a numeric version of a column."""
    if column not in df.columns:
        return pd.Series(dtype="float64")

    return pd.to_numeric(
        df[column],
        errors="coerce",
    )


def _mean(
    df: pd.DataFrame,
    column: str,
) -> Optional[float]:
    """Calculate a safe mean."""
    values = _numeric_column(
        df,
        column,
    ).dropna()

    if values.empty:
        return None

    return float(values.mean())


def _percentage(
    df: pd.DataFrame,
    column: str,
) -> Optional[float]:
    """
    Calculate the percentage of truthy values.

    Supports:
        True / False
        1 / 0
        yes / no
        true / false
    """

    if column not in df.columns or df.empty:
        return None

    series = df[column]

    if pd.api.types.is_bool_dtype(series):
        return float(series.mean() * 100)

    normalized = (
        series
        .astype(str)
        .str.strip()
        .str.lower()
    )

    truthy = normalized.isin(
        {
            "true",
            "1",
            "yes",
            "y",
            "correct",
            "hit",
            "matched",
            "found",
            "supported",
        }
    )

    return float(truthy.mean() * 100)


# ============================================================================
# OVERALL METRICS
# ============================================================================

def calculate_overall_metrics(
    df: Optional[pd.DataFrame] = None,
) -> dict:
    """
    Calculate the main answer-quality metrics.

    The column names intentionally match the current evaluator output.
    """

    if df is None:
        df = load_answer_quality_results()

    return {
        "total_questions": len(df),

        # Current evaluator column:
        "expected_source_hit_rate": _percentage(
            df,
            "expected_source_found",
        ),

        # Current evaluator column:
        "abstention_accuracy": _percentage(
            df,
            "abstention_correct",
        ),

        "groundedness_mean": _mean(
            df,
            "groundedness_score",
        ),

        "context_relevance_mean": _mean(
            df,
            "context_relevance_score",
        ),

        "citation_correctness": _percentage(
            df,
            "citation_correct",
        ),

        # Current evaluator column:
        "suspicious_answer_rate": _percentage(
            df,
            "suspicious_content",
        ),

        "avg_answer_length": _mean(
            df,
            "answer_length",
        ),

        "avg_retrieval_ms": _mean(
            df,
            "retrieval_ms",
        ),

        "avg_generation_ms": _mean(
            df,
            "generation_ms",
        ),

        "avg_total_ms": _mean(
            df,
            "total_ms",
        ),
    }


# ============================================================================
# GROUPED ANALYSIS
# ============================================================================

def _group_metrics(
    df: pd.DataFrame,
    group_column: str,
) -> pd.DataFrame:
    """Create grouped answer-quality metrics."""

    if group_column not in df.columns:
        return pd.DataFrame()

    rows = []

    for group_value, group in df.groupby(
        group_column,
        dropna=False,
    ):
        rows.append(
            {
                group_column: group_value,

                "total_questions": len(group),

                "expected_source_hit_rate": _percentage(
                    group,
                    "expected_source_found",
                ),

                "abstention_accuracy": _percentage(
                    group,
                    "abstention_correct",
                ),

                "groundedness": _mean(
                    group,
                    "groundedness_score",
                ),

                "context_relevance": _mean(
                    group,
                    "context_relevance_score",
                ),

                "citation_correctness": _percentage(
                    group,
                    "citation_correct",
                ),

                "suspicious_answer_rate": _percentage(
                    group,
                    "suspicious_content",
                ),

                "avg_answer_length": _mean(
                    group,
                    "answer_length",
                ),

                "avg_retrieval_ms": _mean(
                    group,
                    "retrieval_ms",
                ),

                "avg_generation_ms": _mean(
                    group,
                    "generation_ms",
                ),

                "avg_total_ms": _mean(
                    group,
                    "total_ms",
                ),
            }
        )

    return pd.DataFrame(rows)


def difficulty_metrics(
    df: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """Return answer-quality metrics grouped by difficulty."""

    if df is None:
        df = load_answer_quality_results()

    return _group_metrics(
        df,
        "difficulty",
    )


def category_metrics(
    df: Optional[pd.DataFrame] = None,
) -> pd.DataFrame:
    """Return answer-quality metrics grouped by category."""

    if df is None:
        df = load_answer_quality_results()

    return _group_metrics(
        df,
        "category",
    )


# ============================================================================
# WEAKEST QUESTIONS
# ============================================================================

def weakest_questions(
    df: Optional[pd.DataFrame] = None,
    limit: int = 10,
) -> pd.DataFrame:
    """
    Return questions with the weakest combined evidence quality.

    Evidence quality is calculated as:

        (groundedness + context relevance) / 2

    This is a diagnostic evidence-support metric and should not be
    interpreted as a definitive factual correctness score.
    """

    if df is None:
        df = load_answer_quality_results()

    if df.empty:
        return df.copy()

    result = df.copy()

    groundedness = _numeric_column(
        result,
        "groundedness_score",
    ).fillna(0)

    context_relevance = _numeric_column(
        result,
        "context_relevance_score",
    ).fillna(0)

    result["evidence_quality_score"] = (
        groundedness + context_relevance
    ) / 2

    columns = [
        "question",
        "difficulty",
        "category",
        "evidence_quality_score",
        "groundedness_score",
        "context_relevance_score",
        "expected_source_found",
        "citation_correct",
        "answer",
    ]

    available_columns = [
        column
        for column in columns
        if column in result.columns
    ]

    return (
        result
        .sort_values(
            "evidence_quality_score",
            ascending=True,
        )
        .head(limit)[available_columns]
        .reset_index(drop=True)
    )


# ============================================================================
# STRONGEST QUESTIONS
# ============================================================================

def strongest_questions(
    df: Optional[pd.DataFrame] = None,
    limit: int = 10,
) -> pd.DataFrame:
    """Return questions with the strongest evidence quality."""

    if df is None:
        df = load_answer_quality_results()

    if df.empty:
        return df.copy()

    result = df.copy()

    groundedness = _numeric_column(
        result,
        "groundedness_score",
    ).fillna(0)

    context_relevance = _numeric_column(
        result,
        "context_relevance_score",
    ).fillna(0)

    result["evidence_quality_score"] = (
        groundedness + context_relevance
    ) / 2

    columns = [
        "question",
        "difficulty",
        "category",
        "evidence_quality_score",
        "groundedness_score",
        "context_relevance_score",
        "expected_source_found",
        "citation_correct",
        "answer",
    ]

    available_columns = [
        column
        for column in columns
        if column in result.columns
    ]

    return (
        result
        .sort_values(
            "evidence_quality_score",
            ascending=False,
        )
        .head(limit)[available_columns]
        .reset_index(drop=True)
    )


# ============================================================================
# LATENCY
# ============================================================================

def latency_metrics(
    df: Optional[pd.DataFrame] = None,
) -> dict:
    """Return latency statistics for the evaluation run."""

    if df is None:
        df = load_answer_quality_results()

    retrieval = _numeric_column(
        df,
        "retrieval_ms",
    )

    generation = _numeric_column(
        df,
        "generation_ms",
    )

    total = _numeric_column(
        df,
        "total_ms",
    )

    return {
        "retrieval_mean_ms": (
            float(retrieval.mean())
            if not retrieval.dropna().empty
            else None
        ),

        "generation_mean_ms": (
            float(generation.mean())
            if not generation.dropna().empty
            else None
        ),

        "total_mean_ms": (
            float(total.mean())
            if not total.dropna().empty
            else None
        ),

        "retrieval_min_ms": (
            float(retrieval.min())
            if not retrieval.dropna().empty
            else None
        ),

        "retrieval_max_ms": (
            float(retrieval.max())
            if not retrieval.dropna().empty
            else None
        ),

        "generation_min_ms": (
            float(generation.min())
            if not generation.dropna().empty
            else None
        ),

        "generation_max_ms": (
            float(generation.max())
            if not generation.dropna().empty
            else None
        ),

        "total_min_ms": (
            float(total.min())
            if not total.dropna().empty
            else None
        ),

        "total_max_ms": (
            float(total.max())
            if not total.dropna().empty
            else None
        ),
    }


# ============================================================================
# DISPLAY HELPERS
# ============================================================================

def format_percentage(
    value: Optional[float],
) -> str:
    """Format a percentage."""
    if value is None:
        return "N/A"

    return f"{value:.2f}%"


def format_score(
    value: Optional[float],
) -> str:
    """Format a 0–1 score as a percentage."""

    if value is None:
        return "N/A"

    return f"{value * 100:.2f}%"


def format_ms(
    value: Optional[float],
) -> str:
    """Format milliseconds."""

    if value is None:
        return "N/A"

    return f"{value:.2f} ms"


# ============================================================================
# MODULE SELF-CHECK
# ============================================================================

if __name__ == "__main__":

    print("=" * 80)
    print("DOCMIND — ANSWER QUALITY ANALYTICS")
    print("=" * 80)

    if not results_exist():
        print(
            f"\nResults file not found:\n"
            f"{RESULTS_PATH}"
        )

        print(
            "\nRun:\n"
            "python -m app.evaluation.answer_evaluator"
        )

        raise SystemExit(1)

    results = load_answer_quality_results()

    print(
        f"\nResults: {len(results)} questions"
    )

    print("\nOVERALL")
    print(
        calculate_overall_metrics(
            results
        )
    )

    print("\nBY DIFFICULTY")
    print(
        difficulty_metrics(
            results
        ).to_string(index=False)
    )

    print("\nBY CATEGORY")
    print(
        category_metrics(
            results
        ).to_string(index=False)
    )

    print("\nWEAKEST QUESTIONS")
    print(
        weakest_questions(
            results
        ).to_string(index=False)
    )