"""
DocMind RAG - Answer Service

This module connects:

    User Question
            ↓
    Hybrid Retrieval
            ├── Dense Semantic Retrieval
            └── BM25 Lexical Retrieval
                    ↓
                Score Fusion
                    ↓
            Cross-Encoder Reranking
                    ↓
            Retrieved Chunks
                    ↓
            Context Builder
                    ↓
            Grounded Prompt
                    ↓
            Ollama Cloud LLM
                    ↓
        Answer + Authoritative Sources

Important:

The LLM generates the answer, but this service owns the source metadata.

We do not rely on the LLM to generate source numbers or filenames.

The original dense Retriever remains available as a fallback.
"""

from __future__ import annotations

from typing import Any
import re

from app.embeddings.embedding_service import EmbeddingService
from app.generation.llm import OllamaCloud
from app.generation.prompts import (
    SYSTEM_PROMPT,
    build_user_prompt,
)
from app.retrieval.hybrid_retriever import HybridRetriever
from app.retrieval.retriever import Retriever


ABSTENTION_MESSAGE = "I don't know based on the available documents."


class AnswerService:
    """
    End-to-end RAG answer service.

    Responsibilities:

    - Retrieve relevant chunks.
    - Build grounded context.
    - Send context + question to the LLM.
    - Return the generated answer.
    - Return authoritative source metadata from retrieval.

    Retrieval modes:

    - Hybrid + Cross-Encoder Reranker: default.
    - Dense-only Retriever: fallback/experimental mode.

    The embedding model is shared between the dense and hybrid
    retrievers so it is loaded only once.
    """

    def __init__(
        self,
        top_k: int = 3,
        use_hybrid: bool = True,
        candidate_k: int = 10,
        dense_weight: float = 0.6,
        bm25_weight: float = 0.4,
        use_reranker: bool = True,
    ):
        if top_k < 1:
            raise ValueError(
                "top_k must be at least 1."
            )

        if candidate_k < top_k:
            raise ValueError(
                "candidate_k must be greater than or equal to top_k."
            )

        if dense_weight < 0 or bm25_weight < 0:
            raise ValueError(
                "dense_weight and bm25_weight cannot be negative."
            )

        if dense_weight == 0 and bm25_weight == 0:
            raise ValueError(
                "At least one retrieval weight must be greater than zero."
            )

        self.top_k = top_k
        self.use_hybrid = use_hybrid
        self.candidate_k = candidate_k
        self.dense_weight = dense_weight
        self.bm25_weight = bm25_weight
        self.use_reranker = use_reranker

        # ------------------------------------------------------------
        # Shared embedding service
        # ------------------------------------------------------------

        # Load the Sentence Transformer embedding model ONCE.
        #
        # Both Retriever and HybridRetriever receive this same
        # instance, avoiding duplicate model loading.
        self.embedding_service = EmbeddingService()

        # ------------------------------------------------------------
        # Retrieval services
        # ------------------------------------------------------------

        # Original dense retriever is intentionally preserved.
        self.dense_retriever = Retriever(
            embedding_service=self.embedding_service,
        )

        # Hybrid retrieval combines:
        #
        #   Dense semantic retrieval
        #   BM25 lexical retrieval
        #   Cross-encoder reranking
        #
        # It reuses the same embedding service.
        self.hybrid_retriever = HybridRetriever(
            dense_weight=dense_weight,
            bm25_weight=bm25_weight,
            embedding_service=self.embedding_service,
        )

        # Backward-compatible alias.
        #
        # Existing code that accesses service.retriever will continue
        # to work and will use the selected retrieval mode.
        self.retriever = (
            self.hybrid_retriever
            if self.use_hybrid
            else self.dense_retriever
        )

        # ------------------------------------------------------------
        # LLM
        # ------------------------------------------------------------

        self.llm = OllamaCloud()

    def build_context(
        self,
        results: list[dict[str, Any]],
    ) -> str:
        """
        Convert retrieved chunks into structured context for the LLM.

        The source metadata is explicitly included so the model can
        understand where each piece of information came from.

        However, source citations are NOT generated by the model.
        The original metadata remains authoritative in the returned
        result.
        """

        if not results:
            return ""

        context_parts: list[str] = []

        for index, result in enumerate(
            results,
            start=1,
        ):
            metadata = result.get(
                "metadata",
                {},
            )

            filename = (
                metadata.get("filename")
                or result.get("filename")
                or "Unknown document"
            )

            category = (
                metadata.get("category")
                or result.get("category")
                or "unknown"
            )

            page = metadata.get(
                "page",
                result.get("page"),
            )

            chunk_number = metadata.get(
                "chunk_number",
                result.get("chunk_number"),
            )

            content = (
                result.get("text")
                or result.get("content")
                or ""
            ).strip()

            if page in (None, -1):
                page_display = "N/A"
            else:
                page_display = str(page)

            if chunk_number is None:
                chunk_display = "N/A"
            else:
                chunk_display = str(chunk_number)

            context_parts.append(
                f"""
--- Retrieved Chunk {index} ---

Document: {filename}

Category: {category}

Page: {page_display}

Chunk: {chunk_display}

Content:

{content}
""".strip()
            )

        return "\n\n".join(context_parts)

    def _build_sources(
        self,
        results: list[dict[str, Any]],
    ) -> list[dict[str, Any]]:
        """
        Build authoritative source metadata from retrieval results.

        These sources come directly from Chroma/retrieval metadata
        rather than from anything generated by the LLM.
        """

        sources: list[dict[str, Any]] = []

        for index, result in enumerate(
            results,
            start=1,
        ):
            metadata = result.get(
                "metadata",
                {},
            )

            filename = (
                metadata.get("filename")
                or result.get("filename")
                or "Unknown document"
            )

            page = metadata.get(
                "page",
                result.get("page"),
            )

            category = metadata.get(
                "category",
                result.get("category"),
            )

            chunk_number = metadata.get(
                "chunk_number",
                result.get("chunk_number"),
            )

            # Prefer the original Chroma distance when available.
            # Hybrid retrieval may additionally provide
            # hybrid/reranker scores.
            distance = result.get("distance")

            # Chroma uses -1 for documents where a page number
            # does not exist.
            if page == -1:
                page = None

            source = {
                "source_number": index,
                "filename": filename,
                "page": page,
                "category": category,
                "chunk_number": chunk_number,
                "distance": distance,
            }

            # Preserve additional retrieval diagnostics when supplied
            # by HybridRetriever. These do not affect authoritative
            # source identity.

            if result.get("hybrid_score") is not None:
                source["hybrid_score"] = result.get(
                    "hybrid_score"
                )

            if result.get("reranker_score") is not None:
                source["reranker_score"] = result.get(
                    "reranker_score"
                )

            if result.get("dense_score") is not None:
                source["dense_score"] = result.get(
                    "dense_score"
                )

            if result.get("bm25_score") is not None:
                source["bm25_score"] = result.get(
                    "bm25_score"
                )

            sources.append(source)

        return sources

    def _normalize_answer(
        self,
        answer: str,
    ) -> str:
        """
        Clean up the LLM response without changing its factual content.

        The model is instructed not to create source citations.
        This method also removes common citation markers if an LLM
        produces them anyway.

        We intentionally do NOT rewrite factual content.
        """

        if not answer:
            return ABSTENTION_MESSAGE

        cleaned = answer.strip()

        if not cleaned:
            return ABSTENTION_MESSAGE

        # If the model accidentally includes our citation marker
        # despite the prompt, remove only the marker.
        #
        # Source information is displayed separately from
        # authoritative metadata.

        cleaned = re.sub(
            r"【\s*\*Source\*\d+\s*】",
            "",
            cleaned,
            flags=re.IGNORECASE,
        )

        cleaned = re.sub(
            r"\[\s*\*Source\*\d+\s*\]",
            "",
            cleaned,
            flags=re.IGNORECASE,
        )

        # Collapse excessive spaces/tabs while preserving normal
        # line breaks and Markdown formatting.
        cleaned = re.sub(
            r"[ \t]{2,}",
            " ",
            cleaned,
        )

        cleaned = re.sub(
            r"\n[ \t]+\n",
            "\n\n",
            cleaned,
        )

        return cleaned.strip() or ABSTENTION_MESSAGE

    def _retrieve(
        self,
        question: str,
    ) -> list[dict[str, Any]]:
        """
        Retrieve chunks using the configured retrieval strategy.
        """

        if self.use_hybrid:
            return self.hybrid_retriever.retrieve(
                query=question,
                top_k=self.top_k,
                candidate_k=self.candidate_k,
                use_reranker=self.use_reranker,
            )

        return self.dense_retriever.retrieve(
            question,
            self.top_k,
        )

    def get_retrieval_mode(self) -> str:
        """
        Return a human-readable description of the active
        retrieval mode.
        """

        if not self.use_hybrid:
            return "Dense Semantic Retrieval"

        if self.use_reranker:
            return (
                "Hybrid Dense + BM25 + Cross-Encoder Reranker"
            )

        return "Hybrid Dense + BM25"

    def ask(
        self,
        question: str,
    ) -> dict[str, Any]:
        """
        Answer a user question using the RAG pipeline.

        Returns:

            {
                "question": str,
                "answer": str,
                "sources": list[dict],
                "retrieved_count": int,
                "top_k": int,
                "retrieval_mode": str
            }
        """

        question = question.strip()

        if not question:
            raise ValueError(
                "Question cannot be empty."
            )

        # ------------------------------------------------------------
        # 1. Retrieve relevant document chunks
        # ------------------------------------------------------------

        results = self._retrieve(
            question
        )

        # ------------------------------------------------------------
        # 2. Build authoritative source metadata
        # ------------------------------------------------------------

        sources = self._build_sources(
            results
        )

        # ------------------------------------------------------------
        # 3. Build context
        # ------------------------------------------------------------

        context = self.build_context(
            results
        )

        # ------------------------------------------------------------
        # 4. Handle empty retrieval safely
        # ------------------------------------------------------------

        if not results or not context:
            return {
                "question": question,
                "answer": ABSTENTION_MESSAGE,
                "sources": [],
                "retrieved_count": 0,
                "top_k": self.top_k,
                "retrieval_mode": self.get_retrieval_mode(),
            }

        # ------------------------------------------------------------
        # 5. Build grounded prompt
        # ------------------------------------------------------------

        user_prompt = build_user_prompt(
            question=question,
            context=context,
        )

        # ------------------------------------------------------------
        # 6. Generate answer using Ollama Cloud
        # ------------------------------------------------------------

        answer = self.llm.chat(
            system_prompt=SYSTEM_PROMPT,
            user_prompt=user_prompt,
        )

        # ------------------------------------------------------------
        # 7. Normalize answer
        # ------------------------------------------------------------

        answer = self._normalize_answer(
            answer
        )

        # ------------------------------------------------------------
        # 8. Return answer + authoritative sources
        # ------------------------------------------------------------

        return {
            "question": question,
            "answer": answer,
            "sources": sources,
            "retrieved_count": len(results),
            "top_k": self.top_k,
            "retrieval_mode": self.get_retrieval_mode(),
        }


def answer_question(
    question: str,
    top_k: int = 3,
) -> dict[str, Any]:
    """
    Convenience function for one-off questions.

    Example:

        result = answer_question(
            "How many annual leave days do employees receive?"
        )

        print(result["answer"])
        print(result["sources"])
    """

    service = AnswerService(
        top_k=top_k
    )

    return service.ask(
        question
    )